services:
  database:
    image: postgres:16.7
    container_name: cats-database
    volumes:
      - cats-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1
    env_file:
      - .env
    ports:
      - "1000:8080"
    depends_on:
      - database

volumes:
  cats-db: